name: django
channels:
  - conda-forge
  - defaults
dependencies:
  - asgiref=3.5.*
  - ca-certificates=2022.10.11
  - certifi=2022.12.7
  - cryptography=38.0.*
  - django=4.1
  - django-extensions=3.2.*
  - djangorestframework=3.14.*
  - freetype=2.12.*
  - ncurses=6.3
  - openssl
  - pillow=9.3.*
  - pip
  - pycparser=2.21
  - pyjwt=2.6.0
  - python=3.9.15
  - pytz=2022.7.1
  - readline=8.2
  - setuptools=65.6.*
  - sqlite=3.40.*
  - sqlparse=0.4.*
  - tk=8.6.*
  - tzdata
  - wheel=0.37.*
  - zlib=1.2.*
  - zstd=1.5.*
  - pip:
    - django-countries==7.5
    - django-rest-knox==4.2.0
    - django-rest-passwordreset==1.3.0
    - typing-extensions==4.4.0
